name: PR Preview Deploy

on:
  workflow_run:
    workflows: ['PR Preview Build']
    types:
    - completed

jobs:
  deploy:
    name: Deploy
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: gravity-ui/preview-deploy-action@v1
      with:
        project: uikit
        github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
        s3-key-id: ${{ secrets.STORYBOOK_S3_KEY_ID }}
        s3-secret-key: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
