name: Release V5

on:
  push:
    branches: [v5]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/release-action@v1
        with:
          github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          node-version: 18
          default-branch: v5
          npm-dist-tag: untagged
          skip-github-release: true
          skip-labeling: true
